### ISSUE TITLE
No

### ISSUE THREAD

**Issue by nhevia** [FdelMazo/usted_avalo#1]
Al final no supe si la bomba fue avalada o no. Ayuda

**Comment by komod0** [comment]
usted se tiene que arrepentir de este issue

**Comment by nhevia** [comment]
Actualizo con reproduccion de incidente.

Esto pasa cuando intento mergear la branch viale-v4 con samid-dev-mobile

![image](https://user-images.githubusercontent.com/50466554/93692087-dde2a500-faee-11ea-9887-f32859003abe.png)

No quiero que pase.

**Comment by nhevia** [comment]
Hay cosas que es mejor no saber.
